### ISSUE TITLE
Cannot get ColorTint GUI to work

### ISSUE THREAD

**Issue by neihcnim** [MattByName/color-tint#19]
When I click on at https://extensions.gnome.org/extension/1471/tint-all/ using Firefox on Ubuntu 20.04, nothing happens.  What should I be seeing?

When I open extensions applications I cannot enable ColorTint.

However, I came across
https://askubuntu.com/questions/1012905/how-do-i-make-my-display-grayscale/1404343#1404343
and was able to change the xgamma values.

What would be the grayscale xgamma values?

Thanks!

**Comment by MattByName** [comment]
Hi!

I'm not familiar with the xgamma command or the tintall extension.

Is there an error shown when you try to enable ColorTint? Which version of GNOME are you using?

**Comment by MattByName** [comment]
@neihcnim I think it's installing an old version of the extension for you. I've just verified the current release on ubuntu 20.04, and submitted it to the extensions website. Once that's accepted, you should be able to download and used the new version :smile_cat:

**Comment by MattByName** [comment]
Version 12 in the extensions website is now available. If you update everything should work fine :)

Thanks for getting it touch!
