### ISSUE TITLE
Unable to rearrange apps in dock with ColorTint 2.3.0 and Ubuntu 22.04

### ISSUE THREAD

**Issue by fury182** [MattByName/color-tint#23]
If the extension is active, I am unable to rearrange apps in the dock.

Thanks

**Comment by MattByName** [comment]
Thanks for reporting this! I'm hoping to have this fixed in the coming months. Pressing Esc allows you to leave the drag and drop, and toggling off the tint allows you to move items in the dock and apps view

Closing as same issue as [#20](https://github.com/MattByName/color-tint/issues/20)
