### ISSUE TITLE
Support for Gnome 44

### ISSUE THREAD

**Issue by alexjuda** [MattByName/color-tint#24]
Hi! It would be great to use Color Tint with the latest releases of Gnome. However, this extension can't be used on Fedora 38 because Gnome 44 is unsupported. See the attached screenshot of Gnome Extension Manager.

![image](https://user-images.githubusercontent.com/6004040/234977496-2421fe35-edc9-40ec-9f9b-2f96197ce01f.png)

**Comment by MattByName** [comment]
Thanks for posting this! GNOME 44 is now supported as of [release v2.3.1] and should now be available as an update through the GNOME Extensions app
