### ISSUE TITLE
Gnome 45 Update

### ISSUE THREAD

**Issue by calhix** [MattByName/color-tint#26]
Hello, any chance for an update? I love this extension as night light doesn't work (Asahi Linux) and this is the next best thing. I wouldn't have updated to Fedora 39 had I known this wasn't yet compatible. Thank you.

**Comment by MattByName** [comment]
I've started work on porting to Gnome 45. It needs more changes than I thought, but I should have this done by the end of the week.

**Comment by calhix** [comment]
No problem thanks for the help!

**Comment by MattByName** [comment]
[New release](https://github.com/MattByName/color-tint/releases/tag/v2.3.2) is ported to GNOME 45 and already in extensions store.
